sudo: required
services:
  - docker

before_install:
  - docker build -t konstantainer/docker-react:test -f Dockerfile.dev .

script:
  - docker run -e CI=true konstantainer/docker-react:test npm run test -- --coverage